# Generated by Django 2.1 on 2018-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0002_auto_20180806_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_identifier',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='participant_result_identifier',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
