# Generated by Django 2.1 on 2018-08-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0003_auto_20180807_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='participant_result_identifier',
            new_name='participant_identifier',
        ),
    ]
