# Generated by Django 2.1 on 2018-09-05 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0005_auto_20180808_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='result',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
