# Generated by Django 2.1 on 2018-09-05 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0008_auto_20180905_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='result',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='study',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
